name: 'action-get-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - uses: asdf-vm/actions/setup@v1
    - uses: asdf-vm/actions/plugins-add@v1
    - run: asdf current 2>&1 | grep -v '______' | awk '{print $1 "=" $2}' | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
outputs:
  tool-versions:
    description: 'Parsed .tool-versions'
    value: '${{ steps.parser.outputs }}'
