name: 'action-get-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - uses: asdf-vm/actions/setup@v1
    - uses: asdf-vm/actions/plugins-add@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm ci --ignore-scripts
      shell: bash
    - run: asdf current 2>&1 | grep -v '______' | npx ts-node src/main.ts | echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
outputs:
  tool-versions:
    description: 'Stringified JSON that includes parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
