name: 'action-get-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
        tmpdir="$(mktemp --directory)"
        git clone https://github.com/asdf-vm/asdf.git "$tmpdir" --depth 1 --branch v0.10.2
        "${tmpdir}/bin/asdf" current 2>&1 | grep -v '______' | awk '{print $1 "=" $2}' | tee $GITHUB_OUTPUT
      shell: bash
