name: 'action-parse-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - uses: asdf-vm/actions/setup@v1
    - run: |
        (source "$ASDF_DIR/lib/utils.bash"; strip_tool_version_comments .tool-versions) |
        grep -P '^crystal' | awk '{print "crystal=" $2}' |
        tee --append $GITHUB_OUTPUT
      shell: bash
      id: prepare-runner
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ steps.prepare-runner.outputs.crystal }}
    - run: |
        (source "$ASDF_DIR/lib/utils.bash"; strip_tool_version_comments .tool-versions) |
        crystal run src/main.cr -- jsonize |
        echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
outputs:
  json:
    description: 'Stringified JSON for parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
