name: 'action-get-asdf-tool-versions'
description: 'Parse asdf managed .tool-versions and outputs them'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'eye'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - uses: antongolub/action-setup-bun@v1
    - run: bun install
      shell: bash
    - uses: asdf-vm/actions/setup@v1
    - run: (source "$ASDF_DIR/lib/utils.bash"; strip_tool_version_comments .tool-versions) | bun run jsonizer.ts  | echo "json=$(</dev/stdin)" | tee --append $GITHUB_OUTPUT
      shell: bash
      id: parser
outputs:
  tool-versions:
    description: 'Stringified JSON that includes parsed .tool-versions'
    value: '${{ steps.parser.outputs.json }}'
