name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/crystal.yml'
      - '**/*.cr'
  pull_request:
    paths:
      - '.github/crystal.yml'
      - '**/*.cr'
  workflow_dispatch:

jobs:
  crystal:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format --check
      - run: crystal spec
