name: Validate
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/auto-merge-dependabot-prs.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/auto-merge-dependabot-prs.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  validate: # make sure the action works on a clean machine
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: asdf_parser
      - run: echo "${{ steps.asdf_parser.outputs.tool-versions.shfmt }}"
      - run: echo "${{ steps.asdf_parser.outputs.tool-versions.shellcheck }}"
