name: Validate
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/auto-merge-dependabot-prs.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/auto-merge-dependabot-prs.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./
        id: asdf_parser
    outputs:
      tool-versions: ${{ steps.asdf_parser.outputs.tool-versions }}
  validate: # make sure the action works on a clean machine
    needs: [parser]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "${{ fromJson(needs.parser.outputs.tool-versions).shfmt }}"
      - run: echo "${{ fromJson(needs.parser.outputs.tool-versions).shellcheck }}"
